name: Deploy ML Training Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
    secrets:
      API_KEY_ID:
        required: true
      API_KEY:
        required: true

jobs:
  deploy-staging:
    runs-on: [ubuntu-latest]
    name: Rename testing container in staging and push to staging
    
    timeout-minutes: 30
    
    steps:
    - name: Get Version Tag
      id: get-image-tag
      run: |
        echo "version-tag=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
    - name: Deploy Module to viam-dev Org
      uses: viam-modules/classification-tflite/.github/actions/deploy@DATA-2821/workflows
      with:
        api_key_id: ${{ secrets.API_KEY_ID }}
        api_key: ${{ secrets.API_KEY }}
        framework: tflite
        script_name: classification-tflite
        type: 
        version: ${{ steps.get-image-tag.outputs.version-tag }} 
        org_id: e76d1b3b-0468-4efd-bb7f-fb1d2b352fcb


